# Generated by Django 5.0.1 on 2024-01-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name'], 'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
    ]
