# Generated by Django 5.0.1 on 2024-01-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_num_seats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['trip_date'], 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
    ]
